name: Release

on:
  workflow_call:
    inputs:
      is_prerelease:
        description: Pre-release
        type: boolean
        required: true
      release_tag:
        description: Release tag
        type: string
        required: true
      release_body:
        description: Release description
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download Vulkan artifacts
        uses: actions/download-artifact@v4
        with:
          name: zed-release
          path: artifacts/zed-release
        continue-on-error: true

      - name: Download OpenGL artifacts
        uses: actions/download-artifact@v4
        with:
          name: zed-release-opengl
          path: artifacts/zed-release-opengl
        continue-on-error: true

      - name: Debug - Show artifacts folder structure
        run: |
          echo "Artifacts folder structure:"
          tree artifacts || find artifacts -type f -exec echo {} \; 2>/dev/null || echo "No artifacts folder found"
        continue-on-error: true

      - name: Checkout self (for scripts)
        uses: actions/checkout@v4

      - name: Create release directories and zip
        run: |
          chmod +x scripts/prepare-release.sh
          ./scripts/prepare-release.sh

      - name: Upload release build artifacts to GitHub Release
        uses: softprops/action-gh-release@v2.2.2
        with:
          name: ${{ inputs.release_tag }}
          tag_name: ${{ inputs.release_tag }}
          body: ${{ inputs.release_body }}
          draft: false
          prerelease: ${{ inputs.is_prerelease }}
          make_latest: true
          files: release/*
